#!/bin/bash
#-------------------------------
# Plugin MAnager
# v1.2
# LICENSED UNDER MIT
#-------------------------------

QUERY=`echo $2 | sed 's/ /+/'g`
RESULT=`curl -s https://raw.githubusercontent.com/kreat0/pma-repo/main/vizality.json | jq -r  ".bruh."$QUERY"_link"`

if ! [ -x "$(command -v jq)" ]; then
    echo "jq is not installed, attempting to install it"
    sudo pacman -S jq
    sudo apt install jq 
    sudo zypper install jq
    echo "If it didnt work install  jq manually"
fi

_print_help(){
  cat << "EOF"
Usage:  pma [OPTIONS]
Options:
    -l  --list        List of plugins
    -h  --help        Print help
    -d  --dir         Setup directory 
    -v  --version     Print version
    -f  --fetch       Fetch a plugin
EOF
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    case $1 in
        --dir|-d)
         read DIR
            shift
            shift
            ;;
         --list|-l)
          curl -s https://raw.githubusercontent.com/kreat0/pma-repo/main/vizality.json | jq -r  ".bruh"
            shift
            shift
            ;;
           --version|-v)
            echo "v1.2"
            shift
            ;;
          --fetch|-f)
           cd $DIR
           git clone --progress --quiet $RESULT 
            shift
            shift
            ;;
        --help|-h)
            _print_help
            shift
            shift
            ;;
        *)
          echo "Option not found"
          _print_help
          shift
          ;;
    esac
done
