#!/bin/bash
# ________  _____ ______   ________     
#|\   __  \|\   _ \  _   \|\   __  \    
#\ \  \|\  \ \  \\\__\ \  \ \  \|\  \   
# \ \   ____\ \  \\|__| \  \ \   __  \  
#  \ \  \___|\ \  \    \ \  \ \  \ \  \ 
#   \ \__\    \ \__\    \ \__\ \__\ \__\
#    \|__|     \|__|     \|__|\|__|\|__|
# Plugin MAnager
# v1.6
# LICENSED UNDER MIT

DIR="/the/path/of/plugins/folder"
QUERY=`echo $2 | sed 's/ /+/'g`
RESULT=`curl -s https://pluginmanagerr.github.io/pma-repo/vizality.json | jq -r  ".bruh."$QUERY"_link"`

if ! [ -x "$(command -v jq)" ]; then
    echo "jq is not installed, attempting to install it"
    sudo pacman -S jq
    sudo apt install jq
    sudo emerge -a jq --autounmask
    sudo zypper install jq
    echo "If it didnt work install  jq manually"
fi

if ! [ -x "$(command -v curl)" ]; then
    echo "curl is not installed, attempting to install it"
    sudo pacman -S curl
    sudo apt install curl 
    sudo zypper install curl
    sudo emerge -a curl --autounmask
    echo "If it didnt work install  curl manually"
fi

if ! [ -x "$(command -v git)" ]; then
    echo "git is not installed, attempting to install it"
    sudo pacman -S git
    sudo apt install git 
    sudo zypper install git
    sudo emerge -a git --autounmask
    echo "If it didnt work install  git manually"
fi


_print_help(){
  cat << "EOF"
Usage:  pma [OPTIONS]
Options:
    -i  --install     Install powercord
    -l  --list        List of plugins
    -h  --help        Show help
    -v  --version     Show version
    -f  --fetch       Fetch a plugin
EOF
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
    case $1 in
         --list|-l)
          curl -s https://pluginmanagerr.github.io/pma-repo/vizality.json | jq -r  ".bruh"
            shift
            shift
            ;;
         --install|-i)
      echo "You NEED to have discord canary to proceed, press enter if you do, unless the installer will fail."
      sudo pacman -S nodejs npm
      sudo zypper install node npm
      git clone https://github.com/powercord-org/powercord
      cd powercord
      npm i
      sudo npm run plug
            shift
            shift
            ;;
           --version|-v)
           echo '
 ________  _____ ______   ________     
|\   __  \|\   _ \  _   \|\   __  \    
\ \  \|\  \ \  \\\__\ \  \ \  \|\  \   
 \ \   ____\ \  \\|__| \  \ \   __  \  
  \ \  \___|\ \  \    \ \  \ \  \ \  \ 
   \ \__\    \ \__\    \ \__\ \__\ \__\
    \|__|     \|__|     \|__|\|__|\|__|'              
            echo "v1.6"
            echo "pma is open source, you can check the repos here:"
            echo "https://github.com/pluginmanagerr/pma"
            echo "https://github.com/pluginmanagerr/pma-repo"
            shift
            ;;
          --fetch|-f)
           cd $DIR
           git clone --progress --quiet $RESULT 
            shift
            shift
            ;;
        --help|-h)
            _print_help
            shift
            shift
            ;;
        *)
          echo "Option not found"
          _print_help
          shift
          ;;
    esac
done
